apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-model-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-model
  template:
    metadata:
      labels:
        app: my-model
    spec:
      containers:
      - name: python3-container
        image: mzcasillas97/fproject:latest
        ports:
        - containerPort: 5002  # Update to 5002 to match Flask's internal port
