apiVersion: v1
kind: Service
metadata:
  name: my-model-service
spec:
  selector:
    app: my-model
  ports:
    - protocol: TCP
      port: 80           # Exposes port 80 externally
      targetPort: 5002    # Routes traffic to port 5002 inside the container
  type: NodePort
